# Generated by Django 4.2.30 on 2026-04-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('latest_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_cnt', models.IntegerField()),
                ('data_hex', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('rx_info', models.JSONField()),
                ('tx_info', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='iot_app.device')),
            ],
            options={
                'unique_together': {('device', 'f_cnt')},
            },
        ),
    ]
